relativeURLs = true
LanguageCode = "en-US"
Title = "libp2p"
paginate = 10
DisqusShortname = ""
Copyright = "All rights reserved - 2016"
canonifyurls = true

[params]
  description = "make peer-to-peer great again"
  cover = "images/user.jpg"
  author = "Protocol Labs"
  authorlocation = ""
  authorwebsite = "https://github.com/libp2p/libp2p"
  logo = "images/user.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "libp2p"
  twitterName = "IPFSBot"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
